pipeline {
    agent any
        tools {
         maven 'Maven'
         jdk 'java'
    }

    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
        steps {
            sh '''
                export MAVEN_HOME=/opt/maven
                export PATH=$MAVEN_HOME/bin:$PATH

                java --version
                mvn --version
                mvn -B -DskipTests clean package
            '''
        }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
